// AUTO-GENERATED by scripts/generate-tambo-api-catalog.mjs
// Do not edit manually. Re-run: node scripts/generate-tambo-api-catalog.mjs

export const SITE_ENDPOINT_CATALOG = [
  {
    "path": "/api/*",
    "methods": [
      "GET",
      "POST",
      "PUT",
      "PATCH",
      "DELETE"
    ],
    "description": "Generic caller: any existing /api route can be requested with site_api_request."
  }
] as const;
