// AUTO-GENERATED by scripts/generate-tambo-ui-catalog.mjs
// Do not edit manually. Re-run: node scripts/generate-tambo-ui-catalog.mjs

export const SITE_UI_COMPONENT_CATALOG = [
  {
    "name": "AdminDashboardPage",
    "purpose": "UI component from components admin AdminDashboardPage",
    "source": "components/admin/AdminDashboardPage.tsx"
  },
  {
    "name": "AdminLayout",
    "purpose": "UI component from components layout AdminLayout",
    "source": "components/layout/AdminLayout.tsx"
  },
  {
    "name": "AdminsTab",
    "purpose": "UI component from components admin dashboard tabs content AdminsTab",
    "source": "components/admin/dashboard/tabs-content/AdminsTab.tsx"
  },
  {
    "name": "alert",
    "purpose": "UI component from components ui alert",
    "source": "components/ui/alert.tsx"
  },
  {
    "name": "alert-dialog",
    "purpose": "UI component from components ui alert dialog",
    "source": "components/ui/alert-dialog.tsx"
  },
  {
    "name": "AllowedTabsPicker",
    "purpose": "UI component from components admin dashboard AllowedTabsPicker",
    "source": "components/admin/dashboard/AllowedTabsPicker.tsx"
  },
  {
    "name": "animated-input",
    "purpose": "UI component from components smoothui smoothui animated input index",
    "source": "components/smoothui/smoothui/animated-input/index.tsx"
  },
  {
    "name": "AuthShell",
    "purpose": "UI component from components auth AuthShell",
    "source": "components/auth/AuthShell.tsx"
  },
  {
    "name": "avatar",
    "purpose": "UI component from components ui avatar",
    "source": "components/ui/avatar.tsx"
  },
  {
    "name": "badge",
    "purpose": "UI component from components ui badge",
    "source": "components/ui/badge.tsx"
  },
  {
    "name": "basic-dropdown",
    "purpose": "UI component from components smoothui smoothui basic dropdown index",
    "source": "components/smoothui/smoothui/basic-dropdown/index.tsx"
  },
  {
    "name": "button",
    "purpose": "UI component from components ui button",
    "source": "components/ui/button.tsx"
  },
  {
    "name": "calendar",
    "purpose": "UI component from components ui calendar",
    "source": "components/ui/calendar.tsx"
  },
  {
    "name": "CalendarDateSelector",
    "purpose": "UI component from components admin dashboard shared CalendarDateSelector",
    "source": "components/admin/dashboard/shared/CalendarDateSelector.tsx"
  },
  {
    "name": "CalendarRangeSelector",
    "purpose": "UI component from components admin dashboard shared CalendarRangeSelector",
    "source": "components/admin/dashboard/shared/CalendarRangeSelector.tsx"
  },
  {
    "name": "card",
    "purpose": "UI component from components ui card",
    "source": "components/ui/card.tsx"
  },
  {
    "name": "ChangePasswordModal",
    "purpose": "UI component from components admin ChangePasswordModal",
    "source": "components/admin/ChangePasswordModal.tsx"
  },
  {
    "name": "ChatCenter",
    "purpose": "UI component from components chat ChatCenter",
    "source": "components/chat/ChatCenter.tsx"
  },
  {
    "name": "ChatTab",
    "purpose": "UI component from components chat ChatTab",
    "source": "components/chat/ChatTab.tsx"
  },
  {
    "name": "ChatUnifiedTab",
    "purpose": "UI component from components chat ChatUnifiedTab",
    "source": "components/chat/ChatUnifiedTab.tsx"
  },
  {
    "name": "checkbox",
    "purpose": "UI component from components ui checkbox",
    "source": "components/ui/checkbox.tsx"
  },
  {
    "name": "command",
    "purpose": "UI component from components ui command",
    "source": "components/ui/command.tsx"
  },
  {
    "name": "context-menu",
    "purpose": "UI component from components ui context menu",
    "source": "components/ui/context-menu.tsx"
  },
  {
    "name": "CookingManager",
    "purpose": "UI component from components admin warehouse CookingManager",
    "source": "components/admin/warehouse/CookingManager.tsx"
  },
  {
    "name": "CourierMap",
    "purpose": "UI component from components courier CourierMap",
    "source": "components/courier/CourierMap.tsx"
  },
  {
    "name": "CourierProfile",
    "purpose": "UI component from components courier CourierProfile",
    "source": "components/courier/CourierProfile.tsx"
  },
  {
    "name": "DesktopTabsNav",
    "purpose": "UI component from components admin dashboard DesktopTabsNav",
    "source": "components/admin/dashboard/DesktopTabsNav.tsx"
  },
  {
    "name": "dialog",
    "purpose": "UI component from components ui dialog",
    "source": "components/ui/dialog.tsx"
  },
  {
    "name": "DishesManager",
    "purpose": "UI component from components admin warehouse DishesManager",
    "source": "components/admin/warehouse/DishesManager.tsx"
  },
  {
    "name": "DispatchLeafletMap",
    "purpose": "UI component from components admin orders DispatchLeafletMap",
    "source": "components/admin/orders/DispatchLeafletMap.tsx"
  },
  {
    "name": "DispatchMapPanel",
    "purpose": "UI component from components admin orders DispatchMapPanel",
    "source": "components/admin/orders/DispatchMapPanel.tsx"
  },
  {
    "name": "dropdown-menu",
    "purpose": "UI component from components ui dropdown menu",
    "source": "components/ui/dropdown-menu.tsx"
  },
  {
    "name": "EntityStatusBadge",
    "purpose": "UI component from components admin dashboard shared EntityStatusBadge",
    "source": "components/admin/dashboard/shared/EntityStatusBadge.tsx"
  },
  {
    "name": "FeaturesTab",
    "purpose": "UI component from components admin features FeaturesTab",
    "source": "components/admin/features/FeaturesTab.tsx"
  },
  {
    "name": "FilterToolbar",
    "purpose": "UI component from components admin dashboard shared FilterToolbar",
    "source": "components/admin/dashboard/shared/FilterToolbar.tsx"
  },
  {
    "name": "FinanceTab",
    "purpose": "UI component from components admin FinanceTab",
    "source": "components/admin/FinanceTab.tsx"
  },
  {
    "name": "FormField",
    "purpose": "UI component from components admin dashboard shared FormField",
    "source": "components/admin/dashboard/shared/FormField.tsx"
  },
  {
    "name": "HistoryTable",
    "purpose": "UI component from components admin HistoryTable",
    "source": "components/admin/HistoryTable.tsx"
  },
  {
    "name": "icon-button",
    "purpose": "UI component from components ui icon button",
    "source": "components/ui/icon-button.tsx"
  },
  {
    "name": "IngredientsManager",
    "purpose": "UI component from components admin warehouse IngredientsManager",
    "source": "components/admin/warehouse/IngredientsManager.tsx"
  },
  {
    "name": "input",
    "purpose": "UI component from components ui input",
    "source": "components/ui/input.tsx"
  },
  {
    "name": "InterfaceSettings",
    "purpose": "UI component from components admin InterfaceSettings",
    "source": "components/admin/InterfaceSettings.tsx"
  },
  {
    "name": "label",
    "purpose": "UI component from components ui label",
    "source": "components/ui/label.tsx"
  },
  {
    "name": "LanguageSwitcher",
    "purpose": "UI component from components LanguageSwitcher",
    "source": "components/LanguageSwitcher.tsx"
  },
  {
    "name": "MiddleLiveMap",
    "purpose": "UI component from components admin orders MiddleLiveMap",
    "source": "components/admin/orders/MiddleLiveMap.tsx"
  },
  {
    "name": "MiniLocationPickerMap",
    "purpose": "UI component from components admin dashboard shared MiniLocationPickerMap",
    "source": "components/admin/dashboard/shared/MiniLocationPickerMap.tsx"
  },
  {
    "name": "MobileBottomTabsNav",
    "purpose": "UI component from components admin dashboard MobileBottomTabsNav",
    "source": "components/admin/dashboard/MobileBottomTabsNav.tsx"
  },
  {
    "name": "MobileHeader",
    "purpose": "UI component from components layout MobileHeader",
    "source": "components/layout/MobileHeader.tsx"
  },
  {
    "name": "OrderModal",
    "purpose": "UI component from components admin dashboard modals OrderModal",
    "source": "components/admin/dashboard/modals/OrderModal.tsx"
  },
  {
    "name": "OrdersTable",
    "purpose": "UI component from components admin OrdersTable",
    "source": "components/admin/OrdersTable.tsx"
  },
  {
    "name": "OtpAuthForm",
    "purpose": "UI component from components site OtpAuthForm",
    "source": "components/site/OtpAuthForm.tsx"
  },
  {
    "name": "popover",
    "purpose": "UI component from components ui popover",
    "source": "components/ui/popover.tsx"
  },
  {
    "name": "progress",
    "purpose": "UI component from components ui progress",
    "source": "components/ui/progress.tsx"
  },
  {
    "name": "PWAInstallPrompt",
    "purpose": "UI component from components PWAInstallPrompt",
    "source": "components/PWAInstallPrompt.tsx"
  },
  {
    "name": "PWANetworkStatus",
    "purpose": "UI component from components PWANetworkStatus",
    "source": "components/PWANetworkStatus.tsx"
  },
  {
    "name": "RefreshIconButton",
    "purpose": "UI component from components admin dashboard shared RefreshIconButton",
    "source": "components/admin/dashboard/shared/RefreshIconButton.tsx"
  },
  {
    "name": "right-action-line",
    "purpose": "UI component from components ui right action line",
    "source": "components/ui/right-action-line.tsx"
  },
  {
    "name": "RouteOptimizeButton",
    "purpose": "UI component from components admin RouteOptimizeButton",
    "source": "components/admin/RouteOptimizeButton.tsx"
  },
  {
    "name": "scroll-area",
    "purpose": "UI component from components ui scroll area",
    "source": "components/ui/scroll-area.tsx"
  },
  {
    "name": "search-panel",
    "purpose": "UI component from components ui search panel",
    "source": "components/ui/search-panel.tsx"
  },
  {
    "name": "SectionMetrics",
    "purpose": "UI component from components admin dashboard shared SectionMetrics",
    "source": "components/admin/dashboard/shared/SectionMetrics.tsx"
  },
  {
    "name": "select",
    "purpose": "UI component from components ui select",
    "source": "components/ui/select.tsx"
  },
  {
    "name": "ServiceWorkerRegistration",
    "purpose": "UI component from components ServiceWorkerRegistration",
    "source": "components/ServiceWorkerRegistration.tsx"
  },
  {
    "name": "SetsTab",
    "purpose": "UI component from components admin SetsTab",
    "source": "components/admin/SetsTab.tsx"
  },
  {
    "name": "sheet",
    "purpose": "UI component from components ui sheet",
    "source": "components/ui/sheet.tsx"
  },
  {
    "name": "Sidebar",
    "purpose": "UI component from components layout Sidebar",
    "source": "components/layout/Sidebar.tsx"
  },
  {
    "name": "SiteAuthShell",
    "purpose": "UI component from components site SiteAuthShell",
    "source": "components/site/SiteAuthShell.tsx"
  },
  {
    "name": "SiteBuilderCard",
    "purpose": "UI component from components admin SiteBuilderCard",
    "source": "components/admin/SiteBuilderCard.tsx"
  },
  {
    "name": "SiteContent",
    "purpose": "UI component from components site SiteContent",
    "source": "components/site/SiteContent.tsx"
  },
  {
    "name": "SiteScaffold",
    "purpose": "UI component from components site SiteScaffold",
    "source": "components/site/SiteScaffold.tsx"
  },
  {
    "name": "SiteStyleRendersDialog",
    "purpose": "UI component from components admin SiteStyleRendersDialog",
    "source": "components/admin/SiteStyleRendersDialog.tsx"
  },
  {
    "name": "skeleton",
    "purpose": "UI component from components ui skeleton",
    "source": "components/ui/skeleton.tsx"
  },
  {
    "name": "smoothui",
    "purpose": "UI component from components smoothui index",
    "source": "components/smoothui/index.ts"
  },
  {
    "name": "sonner",
    "purpose": "UI component from components ui sonner",
    "source": "components/ui/sonner.tsx"
  },
  {
    "name": "sortable-header",
    "purpose": "UI component from components ui sortable header",
    "source": "components/ui/sortable-header.tsx"
  },
  {
    "name": "states",
    "purpose": "UI component from components ui states",
    "source": "components/ui/states.tsx"
  },
  {
    "name": "StatsCards",
    "purpose": "UI component from components admin StatsCards",
    "source": "components/admin/StatsCards.tsx"
  },
  {
    "name": "switch",
    "purpose": "UI component from components ui switch",
    "source": "components/ui/switch.tsx"
  },
  {
    "name": "TabEmptyState",
    "purpose": "UI component from components admin dashboard shared TabEmptyState",
    "source": "components/admin/dashboard/shared/TabEmptyState.tsx"
  },
  {
    "name": "table",
    "purpose": "UI component from components ui table",
    "source": "components/ui/table.tsx"
  },
  {
    "name": "table-filter-panel",
    "purpose": "UI component from components ui table filter panel",
    "source": "components/ui/table-filter-panel.tsx"
  },
  {
    "name": "table-filter-utils",
    "purpose": "UI component from components ui table filter utils",
    "source": "components/ui/table-filter-utils.ts"
  },
  {
    "name": "tabMeta",
    "purpose": "UI component from components admin dashboard tabMeta",
    "source": "components/admin/dashboard/tabMeta.ts"
  },
  {
    "name": "tabs",
    "purpose": "UI component from components admin dashboard tabs",
    "source": "components/admin/dashboard/tabs.ts"
  },
  {
    "name": "tabs",
    "purpose": "UI component from components ui tabs",
    "source": "components/ui/tabs.tsx"
  },
  {
    "name": "TamboAgentWidget",
    "purpose": "UI component from components tambo TamboAgentWidget",
    "source": "components/tambo/TamboAgentWidget.tsx"
  },
  {
    "name": "TamboProviderClient",
    "purpose": "UI component from components providers TamboProviderClient",
    "source": "components/providers/TamboProviderClient.tsx"
  },
  {
    "name": "textarea",
    "purpose": "UI component from components ui textarea",
    "source": "components/ui/textarea.tsx"
  },
  {
    "name": "TodaysMenu",
    "purpose": "UI component from components admin TodaysMenu",
    "source": "components/admin/TodaysMenu.tsx"
  },
  {
    "name": "toggle",
    "purpose": "UI component from components ui toggle",
    "source": "components/ui/toggle.tsx"
  },
  {
    "name": "tooltip",
    "purpose": "UI component from components ui tooltip",
    "source": "components/ui/tooltip.tsx"
  },
  {
    "name": "TrialStatus",
    "purpose": "UI component from components admin TrialStatus",
    "source": "components/admin/TrialStatus.tsx"
  },
  {
    "name": "types",
    "purpose": "UI component from components admin dashboard types",
    "source": "components/admin/dashboard/types.ts"
  },
  {
    "name": "useDashboardData",
    "purpose": "UI component from components admin dashboard useDashboardData",
    "source": "components/admin/dashboard/useDashboardData.ts"
  },
  {
    "name": "WarehouseStartPointPickerMap",
    "purpose": "UI component from components admin dashboard shared WarehouseStartPointPickerMap",
    "source": "components/admin/dashboard/shared/WarehouseStartPointPickerMap.tsx"
  },
  {
    "name": "WarehouseTab",
    "purpose": "UI component from components admin WarehouseTab",
    "source": "components/admin/WarehouseTab.tsx"
  }
] as const;

export const SITE_UI_PAGE_CATALOG = [
  {
    "path": "/",
    "purpose": "Interactive page at /"
  },
  {
    "path": "/auth/redirect",
    "purpose": "Interactive page at /auth/redirect"
  },
  {
    "path": "/courier",
    "purpose": "Interactive page at /courier"
  },
  {
    "path": "/login",
    "purpose": "Interactive page at /login"
  },
  {
    "path": "/low-admin",
    "purpose": "Interactive page at /low-admin"
  },
  {
    "path": "/middle-admin",
    "purpose": "Interactive page at /middle-admin"
  },
  {
    "path": "/middle-admin/database",
    "purpose": "Interactive page at /middle-admin/database"
  },
  {
    "path": "/offline",
    "purpose": "Interactive page at /offline"
  },
  {
    "path": "/signup",
    "purpose": "Interactive page at /signup"
  },
  {
    "path": "/sites/[subdomain]",
    "purpose": "Interactive page at /sites/[subdomain]"
  },
  {
    "path": "/sites/[subdomain]/client",
    "purpose": "Interactive page at /sites/[subdomain]/client"
  },
  {
    "path": "/sites/[subdomain]/dashboard",
    "purpose": "Interactive page at /sites/[subdomain]/dashboard"
  },
  {
    "path": "/sites/[subdomain]/history",
    "purpose": "Interactive page at /sites/[subdomain]/history"
  },
  {
    "path": "/sites/[subdomain]/login",
    "purpose": "Interactive page at /sites/[subdomain]/login"
  },
  {
    "path": "/sites/[subdomain]/register",
    "purpose": "Interactive page at /sites/[subdomain]/register"
  },
  {
    "path": "/super-admin",
    "purpose": "Interactive page at /super-admin"
  }
] as const;
